import sys

sys.stdin = open('1.txt')
sys.setrecursionlimit(10000000)
from collections import deque

def bfs(x, y, passed, cnt):
    global maxv
    q = deque([(x, y, passed, cnt)])
    maxv = 0
    while q:
        x, y, passed, cnt = q.popleft()
        for dx, dy in [(1, 0), (0,1), (-1,0),(0,-1)]:
            nx, ny = dx + x, dy + y
            if 0<=nx<N and 0<=ny<M:
                if arr[nx][ny] not in passed:
                    passed.add(arr[nx][ny])
                    q.append((nx, ny, passed, cnt + 1))
                    maxv = max(maxv, cnt)


N, M = map(int, input().split())
arr = [list(input()) for _ in range(N)]
bfs(0,0, set(arr[0][0]), 1)
print(maxv)

'''
8 9
QDTCYRNEF
MFKGIJAXZ
XAGVNZYGR
PPYUUPFKG
JEQVKFEWU
HCBRUZQPJ
YOVJVILYU
INXATSXKE

답 : 24

20 20
ABCDEFGHIJKLMNOPQRST
UVWXYZABCDEFGHIJKLMN
OPQRSTUVWXYZABCDEFGH
IJKLMNOPQRSTUVWXYZAB
CDEFGHIJKLMNOPQRSTUV
WXYZABCDEFGHIJKLMNOP
ABCDEFGHIJKLMNOPQRST
UVWXYZABCDEFGHIJKLMN
OPQRSTUVWXYZABCDEFGH
IJKLMNOPQRSTUVWXYZAB
CDEFGHIJKLMNOPQRSTUV
WXYZABCDEFGHIJKLMNOP
ABCDEFGHIJKLMNOPQRST
UVWXYZABCDEFGHIJKLMN
OPQRSTUVWXYZABCDEFGH
IJKLMNOPQRSTUVWXYZAB
CDEFGHIJKLMNOPQRSTUV
WXYZABCDEFGHIJKLMNOP
ABCDEFGHIJKLMNOPQRST
WXYZABCDEFGHIJKLMNOP



20 20
ABCDEFGHIJKLMNOPQRST
BCDEFGHIJKLMNOPQRSTU
CDEFGHIJKLMNOPQRSTUV
DEFGHIJKLMNOPQRSTUVW
EFGHIJKLMNOPQRSTUVWX
FGHIJKLMNOPQRSTUVWXY
GHIJKLMNOPQRSTUVWXYZ
HIJKLMNOPQRSTUVWXYZZ
IJKLMNOPQRSTUVWXYZZZ
JKLMNOPQRSTUVWXYZZZZ
KLMNOPQRSTUVWXYZZZZZ
LMNOPQRSTUVWXYZZZZZZ
MNOPQRSTUVWXYZZZZZZZ
NOPQRSTUVWXYZZZZZZZZ
OPQRSTUVWXYZZZZZZZZZ
PQRSTUVWXYZZZZZZZZZZ
QRSTUVWXYZZZZZZZZZZZ
RSTUVWXYZZZZZZZZZZZZ
STUVWXYZZZZZZZZZZZZZ
TUVWXYZZZZZZZZZZZZZZ

'''
